---
title: "xsdm quickstart"
author:
  - name: "Angel Luís Robles Fernández"
    affiliation: "Department of Ecology and Evolutionary Biology and Center for Ecological Research, University of Kansas"
  - name: "Daniel C. Reuman"
    affiliation: "Department of Ecology and Evolutionary Biology and Center for Ecological Research, University of Kansas"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{xsdm quickstart}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Angel to draft this.
Quickstart - Very brief orientation to the reason for using the package (variability
and process-oriented SDMs - see the beginning of the xsdmModel document, but the
version here should be much shorter),
then basically gets the user to their first call to optim_mll, and that's it. Write this
later since we have not finalized optim_mll yet. Then at the end it's a brief
outline of the other vignette materials and what orders you might want to read
them in depending on your needs - Dan can write that part.
Mostly aimed at  basic user, but also kinda aimed at the impatient advanced user
who wants to just run some stuff before they then go back and read xsdmModel.
Maybe you also want to have a very short section aimed at the statistically/computationally
sophisticated (advanced) user, too, so they can, say, see the likelihood function for the model
exposed? Probably yes but still thinking that through. Dan can write that section, too.
