#' Convert parameters from the math scale to the biological scale
#'
#' @description
#' Transforms an unconstrained "math-scale" parameter vector into the
#' corresponding biologically interpretable parameters.  The input must be a
#' **named numeric vector** whose names exactly match the canonical schema
#' returned by \code{\link{make_mask_names}(p)} for some integer \eqn{p \ge 1}.
#'
#' The canonical names are (in order):
#' \itemize{
#'   \item \code{mu1, mu2, \ldots, mup}
#'   \item \code{sigltil1, sigltil2, \ldots, sigltilp}
#'   \item \code{sigrtil1, sigrtil2, \ldots, sigrtilp}
#'   \item \code{ctil}
#'   \item \code{pd}
#'   \item \code{o_par1, o_par2, \ldots, o_parq} where \eqn{q = p(p-1)/2}
#' }
#' These are the names generated by \code{\link{make_mask_names}(p)}.
#'
#' @param param_vector A **named** numeric vector of math-scale parameters.
#'   The names must be exactly those returned by \code{\link{make_mask_names}(p)},
#'   and the length must equal \code{\link{num_par}(p)}.  No missing values
#'   are allowed.  Passing an unnamed vector or a vector whose names do not
#'   match the canonical order will raise an error.
#'
#' @returns A named list of biological-scale parameters with elements:
#'   \code{mu}, \code{sigltil}, \code{sigrtil}, \code{ctil}, \code{pd},
#'   \code{o_mat}.
#'
#' @details
#' The transformations applied are:
#' \itemize{
#'   \item \code{mu}: identity (unchanged)
#'   \item \code{sigltil}, \code{sigrtil}: \code{exp()}
#'   \item \code{ctil}: identity (unchanged)
#'   \item \code{pd}: \code{\link{expit}()}
#'   \item \code{o_par}: used to build an orthogonal matrix via
#'         \code{\link{build_orthogonal_matrix}}
#' }
#' For \code{p = 1} there are no \code{o_par} entries; the orthogonal matrix
#' is simply a 1-by-1 identity.
#'
#' This is a thin R wrapper around the internal C++ implementation
#' \code{xsdm:::.math_to_bio_cpp}. The pre-port pure-R implementation is
#' preserved internally as \code{xsdm:::math_to_bio_r} for parity testing.
#'
#' @seealso \code{\link{make_mask_names}}, \code{\link{num_par}},
#'   \code{\link{num_env_var}}, \code{\link{loglik_math}},
#'   \code{\link{bio_to_math}}
#'
#' @export
#'
#' @examples
#' # Create your own vector of parameter for p = 1 (no o_par entries),
#' # We use the function make_mask_names with p = 1 to get the correct names and
#' # length 
#' p1_names <- make_mask_names(1)
#' math_vec <- p1_names
#' math_vec[] <- c(11, log(1.2), log(0.8), -6.7, -1.13)
#' # We get a list with parameters in biological scale
#' math_to_bio(math_vec)
#'
#' # For p = 2 (includes o_par1) -- using the shipped example vector
#' math_to_bio(examples$par_vec)
math_to_bio <- function(param_vector) {
  # R-side validation preserves the historical checkmate-style error
  # messages (which the existing test suite asserts against). The
  # numeric transformations and orthogonal-matrix construction are
  # then delegated to the internal C++ kernel
  # `xsdm:::.math_to_bio_cpp`.
  checkmate::assert_numeric(
    param_vector,
    names = "named",
    any.missing = FALSE,
    min.len = 5  # smallest possible length (p = 1)
  )

  n <- length(param_vector)
  p <- num_env_var(n)  # errors if n is not a valid num_par(p)

  expected_names <- names(make_mask_names(p))
  if (!identical(names(param_vector), expected_names)) {
    stop(
      "`param_vector` names do not match the canonical order for p = ", p, ".\n",
      "Expected: ", paste(expected_names, collapse = ", "), "\n",
      "Received: ", paste(names(param_vector), collapse = ", ")
    )
  }

  .math_to_bio_cpp(
    as.numeric(unlist(param_vector)) |>
      stats::setNames(names(param_vector))
  )
}
