#' Optimize the xsdm log-likelihood from multiple starts (ucminf)
#'
#' Runs multiple ucminf optimizations from starting values generated by
#' \code{start_parms()}, optionally in parallel. Returns one row per start with
#' the achieved log-likelihood, convergence code, and a full math-scale parameter
#' vector (list-column) reconstructed with \code{mask}.
#'
#' @param env_dat 3D array: (locations x time x variables), no NAs.
#' @param occ Logical or integerish 0/1 vector, length = nrow(env_dat).
#' @param mask NULL or named numeric math-scale values to fix.
#' @param num_starts Integer. Number of starting points. Default 100.
#' @param breadth Scalar in \code{[0, 1]} controlling how wide the search
#'   ranges are around their (fixed, data-driven) center. \code{breadth = 1}
#'   (the default) reproduces the pre-v0.3 behaviour that corresponded to
#'   \code{quant_vec = c(0.1, 0.5, 0.9)}; \code{breadth = 0} collapses
#'   every range to essentially a single point, equivalent to
#'   \code{quant_vec = c(0.5 - 1e-6, 0.5, 0.5 + 1e-6)}. Values in between
#'   interpolate linearly.
#' @param parallel Logical. If TRUE, distribute starts via \pkg{future}/\pkg{furrr}.
#' @param num_threads Integer >=1. Threads used inside \code{loglik_math}.
#'   If \code{parallel=TRUE}, consider \code{num_threads=1}.
#' @param control Named list merged into ucminf control. User wins over defaults.
#' @param verbose Logical. If TRUE, prints compact progress messages.
#'
#' @return A list with:
#' \itemize{
#'   \item \code{solutions}: data.frame sorted by decreasing \code{loglik},
#'         columns: \code{start_id}, \code{loglik}, \code{convergence},
#'         and list-column \code{full_par} (complete math-scale vector).
#'   \item \code{best}: list with \code{par} (full math-scale vector),
#'         \code{loglik}, and \code{convergence}.
#' }
#' @export
#' @examples
#' optimize_likelihood(
#'   env_dat = examples$env_array[1:4, , ],
#'   occ = examples$occ_vec[1:4],
#'   num_starts = 4L
#' )
optimize_likelihood <- function(
    env_dat,
    occ,
    mask = NULL,
    num_starts = 100L,
    breadth = 1,
    parallel = FALSE,
    num_threads = RcppParallel::defaultNumThreads(),
    control = list(),
    verbose = FALSE
) {
  # --------------------------
  # Validation
  # --------------------------
  check_env_array(env_dat)
  
  n_loc <- dim(env_dat)[1]
  checkmate::assert(
    checkmate::check_logical(occ, any.missing = FALSE, len = n_loc),
    checkmate::check_integerish(occ, lower = 0, upper = 1, any.missing = FALSE, len = n_loc),
    .var.name = "occ"
  )
  # normalize occ if logical
  if (is.logical(occ)) occ <- as.integer(occ)
  
  checkmate::assert_numeric(mask, any.missing = FALSE, null.ok = TRUE)
  if (!is.null(mask)) {
    checkmate::assert_character(names(mask), any.missing = FALSE, min.len = length(mask), unique = TRUE)
  }
  
  checkmate::assert_integerish(num_starts, lower = 1, any.missing = FALSE, len = 1)
  checkmate::assert_flag(parallel)
  checkmate::assert_integerish(num_threads, lower = 1, any.missing = FALSE, len = 1)
  checkmate::assert_list(control, any.missing = FALSE, null.ok = TRUE)
  
  # --------------------------
  # Merge ucminf controls (user wins)
  # --------------------------
  default_ctrl <- list(
    grad     = "central",
    gradstep = c(1e-6, 1e-8),
    grtol    = 1e-4,
    xtol     = 1e-8,
    stepmax  = 5,
    maxeval  = 2000
  )
  if (is.null(control)) control <- list()
  base_control <- utils::modifyList(default_ctrl, control)
  
  # --------------------------
  # Build starting points (math scale) from presences
  # --------------------------
  env_dat_ex_occ <- env_dat[occ == 1L, , , drop = FALSE]
  if (length(dim(env_dat_ex_occ)) != 3L || dim(env_dat_ex_occ)[1] < 1L) {
    stop("No presences (occ==1) available to construct starting points.", call. = FALSE)
  }
  
  params_table <- start_parms(
    env_dat = env_dat_ex_occ,
    mask = mask,
    num_starts = num_starts,
    breadth  = breadth 
  )
  if (nrow(params_table) < 1L) {
    stop("start_parms() returned no starting points.", call. = FALSE)
  }
  
  
  # -----------------------------------------------
  # convert all starting conditions in canonical  #
  # -----------------------------------------------
  
  
  # Split to a list of named vectors
  list_of_pars <- split(params_table, seq_len(nrow(params_table)))
  list_of_pars <- Map(function(x) {
    v <- unlist(x, use.names = TRUE)
    # ensure numeric and preserve names
    v <- as.numeric(v)
    names(v) <- names(x)
    v
  }, list_of_pars)
  
  
  # --------------------------
  # Runner for a single start
  # --------------------------
  p <- dim(env_dat)[3]
  
  if (parallel && num_threads > 1L) {
    if (verbose) message("parallel=TRUE: forcing num_threads=1 to avoid nested RcppParallel.")
    num_threads <- 1L
  }
  
  runner <- function(start_vec) {
    # Wrap entire body so a single bad starting point returns NULL instead of
    # crashing the whole map (Fix 1). NULL entries are filtered out below
    # before the results are assembled (Fix 2).
    tryCatch(
      {
        # ensure each callr worker remains single-threaded
        RcppParallel::setThreadOptions(numThreads = 1L)
        
        res <- optimize_loglik_math_(
          param_vector = start_vec,
          env_dat      = env_dat,
          occ          = occ,
          mask         = mask,
          num_threads  = 1L,
          base_control = base_control,
          invh_lt      = NULL
        )
        
        full_par <- create_param_vector_masked(res$par, mask, p)
        loglik <- -res$value
        list(full_par = full_par, loglik = loglik, convergence = res$convergence)
      },
      error = function(e) NULL
    )
  }
  
  
  # --------------------------
  # Map over starts (optionally parallel)
  # --------------------------
  if (verbose) {
    message(sprintf(
      "Optimizing from %d starting points%s.",
      num_starts,
      if (parallel) " (parallel)" else ""
    ))
  }
  
  
  if (parallel) {
    for (pkg in c("future", "future.callr", "furrr")) {
      if (!requireNamespace(pkg, quietly = TRUE)) {
        stop(sprintf(
          "Package '%s' is required for parallel optimization. Install it with: install.packages('%s')",
          pkg, pkg
        ))
      }
    }
    old_plan <- future::plan()
    on.exit(future::plan(old_plan), add = TRUE)
    
    future::plan(future.callr::callr, workers = future::availableCores())
    
    res_list <- furrr::future_map(
      list_of_pars, runner,
      .options = furrr::furrr_options(
        packages = c("xsdm", "ucminf", "checkmate", "RcppParallel"),
        seed     = TRUE
      ),
      .progress = TRUE
    )
  } else {
    if (!requireNamespace("purrr", quietly = TRUE)) {
      stop("Package 'purrr' is required for this function. Install it with install.packages('purrr').")
    }
    res_list <- purrr::map(list_of_pars, runner, .progress = TRUE)
  }
  
  # --------------------------
  # Assemble results in profile-like tidy structure
  # --------------------------
  # Filter out NULL entries from starts that failed (Fix 2).
  # Track the failure count so users can be informed via verbose mode.
  ok_list <- Filter(Negate(is.null), res_list)
  n_failed <- length(res_list) - length(ok_list)
  if (n_failed > 0L && verbose) {
    message(sprintf(
      "%d of %d starting %s failed and were excluded.",
      n_failed, length(res_list), if (n_failed == 1L) "point" else "points"
    ))
  }
  if (length(ok_list) == 0L) {
    stop("All starting points failed during optimization.", call. = FALSE)
  }
  
  # rows: one per successful start
  solutions <- data.frame(
    start_id = seq_along(ok_list),
    loglik = vapply(ok_list, function(x) x$loglik, numeric(1)),
    convergence = vapply(ok_list, function(x) {
      cval <- x$convergence
      if (is.null(cval) || !is.finite(cval)) NA_integer_ else as.integer(cval)
    }, integer(1)),
    stringsAsFactors = FALSE
  )
  solutions$full_par <- lapply(ok_list, `[[`, "full_par")
  
  # Sort by decreasing log-likelihood
  ord <- order(solutions$loglik, decreasing = TRUE)
  solutions <- solutions[ord, , drop = FALSE]
  solutions$full_par <- solutions$full_par[ord]
  rownames(solutions) <- NULL
  
  # Best
  best_idx <- 1L
  best <- list(
    par         = solutions$full_par[[best_idx]],
    loglik      = solutions$loglik[[best_idx]],
    convergence = solutions$convergence[[best_idx]]
  )
  
  if (verbose) {
    message(sprintf(
      "Best log-likelihood: %.6f (convergence=%s)",
      best$loglik, as.character(best$convergence)
    ))
  }
  
  list(
    solutions = solutions,
    best      = best
  )
}

#' Internal helper: run ucminf for one starting vector
#' @keywords internal
optimize_loglik_math_ <- function(
    param_vector,  # starting values for FREE params (named)
    env_dat, occ, mask,   # data & fixed params
    num_threads,          # threads for loglik
    base_control,         # list passed to ucminf
    invh_lt = NULL,       # optional inverse Hessian LT warm-start
    optimizer_fun = ucminf::ucminf  # <- dependency injection for testing
) {
  # Merge invH warm-start if provided
  ctrl <- base_control
  if (!is.null(invh_lt)) ctrl$invhessian.lt <- invh_lt
  
  # Run optimizer with protection
  # NOTE: input coercion and validation are inside the tryCatch so that
  # non-finite starting values produce a structured ucminf_error instead of
  # an uncaught assertion failure (Fix 3).
  out <- tryCatch(
    {
      # Ensure numeric & finite par; keep names (inside tryCatch so that
      # non-finite starting values yield a structured ucminf_error — Fix 3)
      v <- as.numeric(param_vector)
      names(v) <- names(param_vector)
      checkmate::assert_numeric(v, any.missing = FALSE, finite = TRUE)
      param_vector <- v
      
      res <- optimizer_fun(
        par      = param_vector,
        fn       = loglik_math,
        env_dat  = env_dat,
        mask     = mask,
        occ      = occ,
        negative = TRUE,
        num_threads = num_threads,
        control  = ctrl,
        hessian  = FALSE
      )
      
      # Restore names if optimizer dropped them
      if (is.null(names(res$par)) && !is.null(names(param_vector))) {
        names(res$par) <- names(param_vector)
      }
      
      # If optimizer returned non-finite params, sanitize and mark custom code
      if (any(!is.finite(res$par))) {
        res$par[!is.finite(res$par)] <- param_vector[!is.finite(res$par)]
        res$convergence <- if (!is.null(res$convergence)) as.integer(res$convergence) else NA_integer_
        res$convergence <- -99L  # custom code for non-finite params
      }
      
      res
    },
    error = function(e) {
      # Structured failure: caller can still assemble results
      structure(
        list(
          par         = param_vector,
          value       = Inf,  # => loglik = -Inf
          convergence = NA_integer_,
          error       = conditionMessage(e)
        ),
        class = "ucminf_error"
      )
    }
  )
  
  out
}