# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.build_orthogonal_matrix_cpp <- function(entries) {
    .Call(`_xsdm_build_orthogonal_matrix_cpp`, entries)
}

#' Compute likelihood for LTSG model
#'
#' This function calculates a likelihood-like measure using orthogonal matrices,
#' environmental data, and diagonal matrices, leveraging parallel computation.
#'
#' @name like_ltsg
#' @title Compute likelihood for LTSG model
#' @param mu Numeric vector of means (length equal to number of rows in `env_m`)
#' @param env_m Numeric matrix of environmental data
#' @param dl_mat Diagonal matrix (as NumericMatrix)
#' @param drl_mat Diagonal matrix (as NumericMatrix)
#' @param ortho_m Numeric matrix (orthogonal basis)
#' @param q Integer, number of rows for reshaping
#' @param r Integer, number of columns for reshaping.
#' @return A numeric vector of length `r` with computed sums.
NULL

like_ltsg <- function(mu, env_m, dl_mat, drl_mat, ortho_m, q, r) {
    .Call(`_xsdm_like_ltsg`, mu, env_m, dl_mat, drl_mat, ortho_m, q, r)
}

#' Compute log detection probabilities from a flat environmental data vector
#'
#' C++ implementation of \code{log_prob_detect()} that accepts environmental
#' data as a flat numeric vector with explicit dimension metadata.  This
#' signature is designed for block-by-block raster evaluation where each
#' block is passed as a contiguous vector rather than a 3-D R array.
#'
#' Collapses the R call chain
#' \code{like_neg_ltsgr_cpp() -> like_ltsg()} into a single xtensor-accelerated
#' C++ function.
#'
#' @param env_dat_vec Numeric vector.  Column-major flat representation of a
#'   3-D array with logical dimensions \code{c(n_loc, ts_length, p)}: variable
#'   \code{k} (1-indexed) occupies positions
#'   \code{(k-1)*n_loc*ts_length + 1} to \code{k*n_loc*ts_length},
#'   and within that block pixels (locations) vary fastest.
#' @param env_dat_dims Integer vector of length 3: \code{c(n_loc, ts_length, p)}.
#' @param mu Numeric vector of length \code{p}.  Optimal environmental values.
#' @param sigltil Numeric vector of length \code{p}.  Positive; \code{Inf}
#'   entries are allowed (treated as zero inverse-scale).
#' @param sigrtil Numeric vector of length \code{p}.  Positive; \code{Inf}
#'   entries are allowed.
#' @param o_mat Numeric matrix, \code{p x p} orthogonal.
#' @param ctil Scalar.  Center of the detection-link function.
#' @param pd Scalar in \code{(0, 1]}.  Maximum probability of detection.
#' @param return_prob Logical.  If \code{TRUE}, return probabilities; if
#'   \code{FALSE} (default) return log-probabilities.
#' @param num_threads Integer.  Number of parallel threads.  \code{0}
#'   (default) uses \code{RcppParallel::defaultNumThreads()}.
#' @return Numeric vector of length \code{n_loc}.
#' @export
log_prob_detect_cpp <- function(env_dat_vec, env_dat_dims, mu, sigltil, sigrtil, o_mat, ctil, pd, return_prob = FALSE, num_threads = 0L) {
    .Call(`_xsdm_log_prob_detect_cpp`, env_dat_vec, env_dat_dims, mu, sigltil, sigrtil, o_mat, ctil, pd, return_prob, num_threads)
}

#' Pure-C++ log-likelihood for the xsdm model (biological-scale parameters)
#'
#' Computes the log-likelihood directly in C++ without any R callback.
#' Equivalent to loglik_bio(..., sum_log_p = TRUE, return_prob = FALSE).
#'
#' @param env_dat_vec Flat numeric vector containing env_dat in column-major
#'   order (as produced by as.vector(env_dat)).
#' @param env_dat_dims Integer vector of length 3: c(n_loc, ts_length, p).
#' @param occ Integer vector of length n_loc, 0 or 1.
#' @param mu Numeric vector, length p.
#' @param sigltil Positive numeric vector, length p.
#' @param sigrtil Positive numeric vector, length p.
#' @param o_mat A p x p orthogonal matrix (column-major).
#' @param ctil Scalar.
#' @param pd Scalar in (0, 1].
#' @param num_threads Number of threads for the inner xtensor kernel
#'   (0 = RcppParallel default).
#' @return Scalar log-likelihood.
#' @export
loglik_bio_cpp <- function(env_dat_vec, env_dat_dims, occ, mu, sigltil, sigrtil, o_mat, ctil, pd, num_threads = 0L) {
    .Call(`_xsdm_loglik_bio_cpp`, env_dat_vec, env_dat_dims, occ, mu, sigltil, sigrtil, o_mat, ctil, pd, num_threads)
}

#' Pure-C++ log-likelihood for the xsdm model (math-scale parameters)
#'
#' Computes the log-likelihood directly in C++ without any R callback in
#' the inner loop. Semantically equivalent to the R function loglik_math.
#'
#' @param param_vector Named numeric vector of math-scale parameters.
#'   When `mask` is NULL, must contain every canonical name for the
#'   dimension p implied by `env_dat`. When `mask` is supplied, contains
#'   only the free (non-masked) parameters.
#' @param env_dat 3D numeric array with dimensions (n_loc, ts_length, p).
#'   No missing values allowed.
#' @param occ Integer or logical vector of length n_loc, 0/1 or FALSE/TRUE.
#' @param mask Optional named numeric vector of fixed parameters.
#' @param negative Logical; if TRUE (default) returns the negative
#'   log-likelihood (the value to be minimized).
#' @param num_threads Integer; 0 leaves the RcppParallel default.
#'
#' @returns A scalar double.
#' @export
loglik_math_cpp <- function(param_vector, env_dat, occ, mask = NULL, negative = TRUE, num_threads = 0L) {
    .Call(`_xsdm_loglik_math_cpp`, param_vector, env_dat, occ, mask, negative, num_threads)
}

make_loglik_math_xptr <- function(env_dat, occ, mask = NULL, num_threads = 1L, grad = "central", gradstep = as.numeric( c(1e-6, 1e-8))) {
    .Call(`_xsdm_make_loglik_math_xptr`, env_dat, occ, mask, num_threads, grad, gradstep)
}

make_loglik_math_xptr_cpp <- function(env_dat, occ, mask, free_names, num_threads = 1L, grad = "central", gradstep = as.numeric( c(1e-6, 1e-8))) {
    .Call(`_xsdm_make_loglik_math_xptr_cpp`, env_dat, occ, mask, free_names, num_threads, grad, gradstep)
}

.math_to_bio_cpp <- function(param_vector) {
    .Call(`_xsdm_math_to_bio_cpp`, param_vector)
}

.build_canonical_param_vector_cpp <- function(param_vector, mask, p) {
    .Call(`_xsdm_build_canonical_param_vector_cpp`, param_vector, mask, p)
}

