# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute likelihood for LTSG model
#'
#' This function calculates a likelihood-like measure using orthogonal matrices,
#' environmental data, and diagonal matrices, leveraging parallel computation.
#'
#' @name like_ltsg
#' @title Compute likelihood for LTSG model
#' @param mu Numeric vector of means (length equal to number of rows in `env_m`)
#' @param env_m Numeric matrix of environmental data
#' @param dl_mat Diagonal matrix (as NumericMatrix)
#' @param drl_mat Diagonal matrix (as NumericMatrix)
#' @param ortho_m Numeric matrix (orthogonal basis)
#' @param q Integer, number of rows for reshaping
#' @param r Integer, number of columns for reshaping.
#' @return A numeric vector of length `r` with computed sums.
NULL

like_ltsg <- function(mu, env_m, dl_mat, drl_mat, ortho_m, q, r) {
    .Call(`_xsdm_like_ltsg`, mu, env_m, dl_mat, drl_mat, ortho_m, q, r)
}

